package Vista;

import java.awt.Color;

public class AsignarPrograma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AsignarPrograma.class.getName());
    Color azul = new Color(41, 51, 92);
    Color hover = new Color(49, 69, 168);

    /**
     * Creates new form AsignarPrograma
     */
    public AsignarPrograma() {
        initComponents();
        Btn_Guardar.setFocusPainted(false);
        Btn_Guardar.setBorderPainted(false);
        Btn_Guardar.setOpaque(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                         

    private void Btn_GuardarMouseExited(java.awt.event.MouseEvent evt) {                                        
        Btn_Guardar.setBackground(azul);
    }         
    private void Btn_GuardarMouseEntered(java.awt.event.MouseEvent evt) {                                         
        Btn_Guardar.setBackground(hover);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton Btn_Guardar;
}
